sudo: required
services:
  - docker

before_install:
  - docker build -t traigysmantas/k8-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true traigysmantas/k8-docker-react npm run test -- --coverage
